### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by JoseeWouters** [fronteers/website#1]
## Description

We want the website to be multilingual, in English and Dutch. New content should always be multilingual, the old content does not have to be translated necessarily.

## Why should we include this?
Because we not only have Dutch speaking members and since we are a W3C member it's important to also have an English website explaining who we are and what we do.

## Additional context

*Happy flow*
- As a user I go to https://www.fronteers.nl
- I see the website is in Dutch
- I switch the language toggle to English
- The content on the website is now in English

## Subtasks
- [ ] setup CMS for bilingual content
- [ ] develop bilingual templates for different content types
- [ ] develop language switch
